# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        yarn up '*'
        yarn dedupe

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update dependencies
        branch: dependency_updates
        title: Update all dependencies
    schedule:
      interval: "weekly"
