const util = require("./util");

const appStatus = () => {
  console.info("sending app_state_update_message");
  util.sendSSE("app_state_update_message", {
    state: "success",
    message: {
      data: [
        {
          id: "albyhub",
          version: "1.17.0",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "btcpayserver",
          version: "v2.2.1",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "btc-rpc-explorer",
          version: "",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "electrs",
          version: "v0.10.6",
          installed: true,
          configured: true,
          status: "online",
          local_ip: "192.168.178.104",
          http_port: null,
          https_port: null,
          https_forced: false,
          https_self_signed: false,
          hidden_service: null,
          address: "http://192.168.178.104:None",
          auth_method: "none",
          details: null,
          error: null
        },
        {
          id: "jam",
          version: "0.3.0",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "lnbits",
          version: "v1.0.0",
          installed: true,
          configured: false,
          status: "online",
          local_ip: "192.168.178.104",
          http_port: "5000",
          https_port: "5001",
          https_forced: true,
          https_self_signed: true,
          hidden_service: "6yuiiklumzhtx64ojfmxgg6uktxixwxvqm4pzqxzchqzd2wo342pjcqd.onion",
          address: "https://192.168.178.104:5001",
          auth_method: "/wallet?usr=8cf15c009331455c941f14d03e051b40",
          details: null,
          error: null
        },
        {
          id: "mempool",
          version: "v3.2.1",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "rtl",
          version: "v0.15.2",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        },
        {
          id: "thunderhub",
          version: "v0.13.31",
          installed: false,
          configured: false,
          status: "offline",
          local_ip: null,
          http_port: null,
          https_port: null,
          https_forced: null,
          https_self_signed: null,
          hidden_service: null,
          address: null,
          auth_method: null,
          details: null,
          error: null
        }
      ],
      errors: [],
      timestamp: Math.floor(Date.now() / 1000)
    }
  });
};

module.exports = { appStatus };
